name: Quality Check

on:
  pull_request:
    branches: [dotnet-9.0.2-debug]
  push:
    branches: [dotnet-9.0.2-debug]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  quality-check:
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version:
          - '9.0.100'
          - '9.0.102'
          - '9.0.103'
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          cache: true
          cache-dependency-path: '**/packages.lock.json'
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install Dependencies
        run: |
          dotnet restore --locked-mode

      - name: Run quality checks
        run: |
          # Check format.
          dotnet format --verify-no-changes

          # Purge some NuGet caches and run tests.
          HARD=true ./scripts/clean-and-test.sh

          # Ensure pack works.
          dotnet pack --no-restore
